# Generated by Django 3.2 on 2021-04-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210420_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winned_by',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='added_item',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
