# Generated by Django 3.2 on 2021-04-20 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210420_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image_url', models.TextField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category')),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
                ('winned_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
