# Generated by Django 3.2 on 2021-04-20 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_category_id_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winned_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
