# Generated by Django 3.2 on 2021-04-20 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_winned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
